In [5]:
%matplotlib inline
import os
import glob
import numpy as np
from scipy import io
import matplotlib.pyplot as plt
import pandas as pd
pd.options.display.max_columns = 10

## Exploratory data analysis

### Loading the data

In [8]:
train_filename = 'data/train.csv'
train_filename = 'data.csv'

In [11]:
data = pd.read_csv(train_filename,sep=';')

In [12]:
data

,education,experience,industry,interest,location,lookin4,offer,skill
0,NaN,NaN,"19,111,53,127",NaN,"Geneva Area, Switzerland","A Mentor,Funding,Co-founders","Co-founders,Investment",NaN
1,NaN,NaN,"125,94,111",NaN,"Paris Area, France","A Mentor,Co-founders,Industry Expertise","Business Partner,Consultancy Work,Internship",NaN
2,NaN,NaN,"94,50",NaN,"Paris Area, France","Clients,Funding,Internship","Exchange of Ideas,Industry Expertise,Investmen...",NaN
3,NaN,NaN,NaN,NaN,Sunnyvale,A New Job,NaN,NaN
4,NaN,Lector,"68,70,103",Photography,Strasbourg,"A New Job,A Mentor,Exchange of Ideas","Consultancy Work,Exchange of Ideas,Freelancing",Funny
5,NaN,NaN,"140,44",NaN,Carentan,"A New Job,A Mentor,Clients,Exchange of Ideas,I...","Exchange of Ideas,Mentorship,Professional Netw...",NaN
6,NaN,NaN,"122,10,105,144,33,96",NaN,"Paris Area, France","Exchange of Ideas,A Mentor,I am hiring","Consultancy Work,Job Positions,Exchange of Ideas",NaN
7,NaN,NaN,"127,94,53,50",NaN,"Paris Area, France","Co-founders,A Mentor,Funding,Internship","Exchange of Ideas,Internship,Investment Opport...",NaN
8,Bioinformatics,"Co-founder & CEO,Co-founder","12,6,96,4,15","Playing Music,Surfing,Outdoor Activities,Entre...",Paris,"Business Partner,Co-founders,Exchange of Ideas...","Consultancy Work,Industry Expertise,Services/P...","Presenting / Selling New Products,Startup Fund..."
9,NaN,NaN,"6,5,4,3,118",NaN,"Paris Area, France","Business Partner,Clients,Co-founders,Exchange ...","Business Partner,Co-founders,Freelancing,Excha...",NaN
10,NaN,NaN,"24,28,6,33,113,115",NaN,Strasbourg,"Exchange of Ideas,Funding,Investment Opportuni...","Exchange of Ideas,Industry Expertise,Socializi...",NaN
11,NaN,NaN,"24,28",NaN,France,"A New Job,A Mentor,Co-founders,Funding,Internship","Business Partner,Co-founders,Internship,Social...",NaN
12,NaN,NaN,"4,123",NaN,"Noida Area, India","A New Job,Clients,Funding,Professional Network...","Professional Networking,Exchange of Ideas,Ment...",NaN
13,NaN,NaN,NaN,NaN,"Copenhagen Area, Capital Region, Denmark",NaN,NaN,NaN
14,NaN,NaN,"25,140,80,38,99,91,6,27,130",NaN,"Paris Area, France","Business Partner,Clients,Exchange of Ideas,Int...","Business Partner,Consultancy Work,Exchange of ...",NaN
15,NaN,NaN,"28,34,80,98,103",NaN,"Paris Area, France","Exchange of Ideas,I am hiring,Professional Net...","Exchange of Ideas,Investment Opportunity,Mento...",NaN
16,NaN,NaN,"10,106,32,113,46,6,34,110,91",NaN,"Warsaw, Masovian District, Poland","Co-founders,Funding,Service/Product Providers,...","Services/Products,Socializing,Business Partner...",NaN
17,NaN,NaN,80,NaN,"Brussels Area, Belgium","I am hiring,Industry Expertise",Exchange of Ideas,NaN
18,NaN,NaN,"36,99",NaN,Other,A Mentor,"Exchange of Ideas,Business Partner,Mentorship,...",NaN
19,NaN,NaN,"111,127,140,80,126",NaN,"Berlin Area, Germany","A New Job,Business Partner,Clients,Exchange of...","Exchange of Ideas,Freelancing,Investment Oppor...",NaN
20,NaN,NaN,"12,18,76,17",NaN,Greater San Diego Area,I am hiring,Mentorship,NaN
21,NaN,NaN,"12,124,14,17,13,70",NaN,"Paris Area, France","A Mentor,Exchange of Ideas,Industry Expertise,...","Business Partner,Exchange of Ideas,Industry Ex...",NaN
22,NaN,NaN,"38,43,143",NaN,France,"A Mentor,Business Partner,Exchange of Ideas,In...","Exchange of Ideas,Services/Products,Socializin...",NaN
23,NaN,NaN,"96,6,80,99,91",NaN,NaN,"A New Job,Clients,Exchange of Ideas,I am hirin...","Consultancy Work,Exchange of Ideas,Job Positio...",NaN
24,NaN,NaN,"124,14,17,13",NaN,"Spokane, Washington Area","Exchange of Ideas,Internship,I am hiring",NaN,NaN
25,NaN,NaN,"127,25,91,30,36",NaN,Greater Los Angeles Area,"A Mentor,Business Partner,Clients,Exchange of ...","Exchange of Ideas,Freelancing,Investment,Mento...",NaN
26,NaN,NaN,"43,42",NaN,Greater New York City Area,"Clients,Exchange of Ideas,I am hiring,Service/...","Exchange of Ideas,Mentorship,Professional Netw...",NaN
27,NaN,NaN,"5,24,112,96,6,8",NaN,"Paris Area, France","A New Job,Exchange of Ideas,I am hiring,Servic...","Socializing,Services/Products",NaN
28,NaN,NaN,"43,47",NaN,France,"A Mentor,Co-founders,Projects,Exchange of Ideas","Exchange of Ideas,Co-founders,Business Partner...",NaN
29,NaN,NaN,96,NaN,Mauritius,"A New Job,A Mentor,Exchange of Ideas,I am hiri...","Business Partner,Exchange of Ideas,Freelancing...",NaN
...,...,...,...,...,...,...,...,...
928,NaN,NaN,"12,70,114",NaN,Paris,"A Mentor,A New Job,Exchange of Ideas","Freelancing,Exchange of Ideas,Consultancy Work",NaN
929,NaN,NaN,"70,12,15","Biotechnologies,Cell Biology,Climbing,Running",Lyon,"A New Job,Exchange of Ideas,Professional Netwo...","Exchange of Ideas,Freelancing,Professional Net...",NaN
930,NaN,NaN,"15,12,14,68,103",NaN,"Paris Area, France","Professional Networking,A New Job,Industry Exp...","Job Positions,Industry Expertise,Business Partner",NaN
931,NaN,NaN,70,NaN,Paris,"A New Job,Professional Networking,Exchange of ...","Talent / Available for Work,Professional Netwo...",NaN
932,NaN,NaN,"70,12,14,15",NaN,Courcouronnes,"A New Job,Exchange of Ideas,Professional Netwo...","Consultancy Work,Professional Networking",NaN
933,NaN,NaN,"75,12,14,17,15",NaN,"Paris Area, France","A New Job,Exchange of Ideas,Professional Netwo...","Exchange of Ideas,Professional Networking,Serv...",NaN
934,"Biology, General,Immunology,Onco-immunology","PhD in onco-immunology,Master degree internship","70,12,15","Travel,Playing Music,Judo,Literature,Music",Paris,"A New Job,Professional Networking","Professional Networking,Talent / Available for...","qPCR,English,Project Management,ELISA,Cell Bio..."
935,NaN,NaN,"66,63,12,17,15",NaN,Paris,"Industry Expertise,Professional Networking,Pro...","Exchange of Ideas,Socializing,Mentorship",NaN
936,NaN,NaN,"12,70,68",NaN,Paris,"A New Job,A Mentor,Industry Expertise,Professi...","Exchange of Ideas,Mentorship,Professional Netw...",NaN
937,NaN,NaN,"15,80,17,11,130",NaN,Puteaux,"A New Job,A Mentor","Exchange of Ideas,Industry Expertise,Consultan...",NaN
938,NaN,NaN,"12,15,14,17,70",NaN,"Paris Area, France","Exchange of Ideas,Industry Expertise,Projects,...","Exchange of Ideas,Industry Expertise,Professio...",NaN
939,NaN,NaN,"70,63,18,54",NaN,Paris,"Professional Networking,A New Job,A Mentor,Exc...","Exchange of Ideas,Professional Networking,Tale...",NaN
940,NaN,NaN,"12,70,100",NaN,"Paris Area, France","Professional Networking,Industry Expertise,A M...","Exchange of Ideas,Socializing,Talent / Availab...",NaN
941,NaN,NaN,"12,68,70,4",Engineering Science,Bures-sur-Yvette,"A New Job,Professional Networking,Projects,Exc...","Consultancy Work,Exchange of Ideas,Freelancing...","Machine Learning Algorithms,Modelling Biologic..."
942,NaN,NaN,"15,12",NaN,Paris,"A Mentor,A New Job,Exchange of Ideas,Professio...","Consultancy Work,Exchange of Ideas,Talent / Av...",NaN
943,"Marketing/Marketing Management, General,Biolog...",NaN,"15,12,17",NaN,Pomponne,"A New Job,Exchange of Ideas,Professional Netwo...","Exchange of Ideas,Professional Networking,Soci...",NaN
944,NaN,NaN,15,NaN,Paris,"A New Job,A Mentor","Exchange of Ideas,Mentorship,Professional Netw...",NaN
945,NaN,NaN,"15,124,12",NaN,Villemomble,"Projects,Socializing,Industry Expertise,A New ...","Socializing,Talent / Available for Work,Exchan...",NaN
946,NaN,NaN,"14,15,13,12,70","Cuisine,Biochemistry",NaN,"Exchange of Ideas,Internship,Professional Netw...","Professional Networking,Talent / Available for...",NaN
947,NaN,NaN,"12,15,114,14,70",Walking,Lyon,"Internship,Socializing","Socializing,Exchange of Ideas",NaN
948,NaN,NaN,"12,15,114,70,54",NaN,Saint-Mard-de-Réno,"Internship,Projects,A New Job,Professional Net...","Socializing,Talent / Available for Work,Exchan...",NaN
949,NaN,NaN,"10,9",NaN,San Diego,"A Mentor,Clients,Exchange of Ideas,A New Job,P...","Professional Networking,Socializing,Talent / A...",NaN
950,NaN,NaN,70,NaN,"Paris Area, France",NaN,NaN,NaN
951,NaN,NaN,6,NaN,Paris,"A Mentor,Co-founders,Exchange of Ideas","Business Partner,Exchange of Ideas,Freelancing",NaN
952,NaN,NaN,126,NaN,"Paris Area, France",Clients,Exchange of Ideas,NaN
953,NaN,NaN,"12,15,14,124,70",NaN,"Paris Area, France","A New Job,A Mentor,Exchange of Ideas,Industry ...","Exchange of Ideas,Socializing,Professional Net...",NaN
954,NaN,NaN,"17,119",NaN,Paris,"Business Partner,Co-founders","Business Partner,Co-founders,Services/Products",NaN
955,NaN,NaN,"80,132,124",NaN,North Bay Village,"A Mentor,Exchange of Ideas,Clients","Mentorship,Consultancy Work,Job Positions",NaN
956,NaN,NaN,"52,135,112,94,58",NaN,NaN,A New Job,"Job Positions,Professional Networking",NaN
957,NaN,NaN,"1,94,52,53,135",NaN,Tijuana,"Projects,A New Job,Professional Networking,Ind...","Exchange of Ideas,Talent / Available for Work,...",NaN

## The pipeline

### Feature extractor

In [15]:
%%file starting_kit_feature_extractor.py
class FeatureExtractor():
    def __init__(self):
        pass
    def fit(self, X_df, y=None):
        X_df.fillna(-1,inplace=True)
    def transform(self, X_df):
        return X_df.values

Overwriting starting_kit_feature_extractor.py

### algo

In [17]:
from sklearn.base import BaseEstimator

class Algo(BaseEstimator):
    def __init__(self):
        pass

    def fit(self, X, y=None):
        pass
    
    def predict(self, X):
        return np.zeros(len(X))

## Local test

In [16]:
!ramp_test_submission

Traceback (most recent call last):
  File "/root/anaconda3/bin/ramp_test_submission", line 11, in <module>
    sys.exit(ramp_test_submission())
  File "/root/anaconda3/lib/python3.6/site-packages/rampwf/utils/command_line.py", line 86, in ramp_test_submission
    retrain=retrain)
  File "/root/anaconda3/lib/python3.6/site-packages/rampwf/utils/testing.py", line 79, in assert_submission
    problem = assert_read_problem(ramp_kit_dir)
  File "/root/anaconda3/lib/python3.6/site-packages/rampwf/utils/testing.py", line 31, in assert_read_problem
    os.path.join(ramp_kit_dir, 'problem.py'))
  File "/root/anaconda3/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 780, in get_code
  File "/root/anaconda3/lib/python3.6/imp.py", line 158, in get_data
    return super().get_data(path)
  File "<frozen importlib._bootstrap_external>", line 832, in get_data
FileNotFoundError: [Errno 2] No such file or directory: './problem.py'